baseURL = "https://caeret.com/"
languageCode = "en-us"
title = "Caeret"
theme = "LeaveIt"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2015
    author = "Caeret"
    avatar = "/images/me/avatar.png"
    subtitle = "Big brother is watching U."
    home_mode = ""

    google_verification = ""

    description = ""
    keywords = ""
    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "caeret"
