baseURL = "https://caeret.com/"
languageCode = "zh"
title = "Caeret"
theme = "LeaveIt"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 5

[params]
    since = 2015
    author = "Caeret"
    avatar = "/images/me/avatar.png"
    subtitle = "keep simple & keep stupid"
    home_mode = "post"

    google_verification = ""

    description = ""
    keywords = ""
    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "caeret"
